const Product = require('../models/Product');

module.exports = () => {
  const products = [
    {
      isim: 'Tavuk Göğsü',
      kalori: 165,
      protein: 31,
      karbonhidrat: 0,
      yag: 3.6,
    },
    {
      isim: 'Spagetti',
      kalori: 221,
      protein: 8,
      karbonhidrat: 43,
      yag: 1.3,
    },
    {
      isim: 'Brokoli',
      kalori: 55,
      protein: 3.7,
      karbonhidrat: 11.2,
      yag: 0.6,
    },
    {
      isim: 'Somon',
      kalori: 206,
      protein: 22,
      karbonhidrat: 0,
      yag: 13.5,
    },
    {
      isim: 'Muz',
      kalori: 105,
      protein: 1.3,
      karbonhidrat: 27,
      yag: 0.4,
    },
    {
      isim: 'Makarna',
      kalori: 180,
      protein: 6.2,
      karbonhidrat: 35,
      yag: 2.1,
    },
    {
      isim: 'Ispanak',
      kalori: 23,
      protein: 2.9,
      karbonhidrat: 3.6,
      yag: 0.4,
    },
    {
      isim: 'Dana Biftek',
      kalori: 250,
      protein: 26,
      karbonhidrat: 0,
      yag: 17,
    },
    {
      isim: 'Portakal',
      kalori: 62,
      protein: 1.2,
      karbonhidrat: 15.4,
      yag: 0.2,
    },
    {
      isim: 'Pirinç',
      kalori: 130,
      protein: 2.7,
      karbonhidrat: 28.7,
      yag: 0.3,
    },
    {
      isim: 'Çikolata Keki',
      kalori: 350,
      protein: 3.2,
      karbonhidrat: 51.8,
      yag: 16.2,
    },
    {
      isim: 'Yoğurt',
      kalori: 100,
      protein: 10,
      karbonhidrat: 7,
      yag: 2.5,
    },
    {
      isim: 'Havuç',
      kalori: 41,
      protein: 0.9,
      karbonhidrat: 10,
      yag: 0.2,
    },
    {
      isim: 'Ton Balığı Salatası',
      kalori: 180,
      protein: 20,
      karbonhidrat: 3,
      yag: 10,
    },
    {
      isim: 'Avokado',
      kalori: 160,
      protein: 2,
      karbonhidrat: 9,
      yag: 14.7,
    },
    {
      isim: 'Yulaf Ezmesi',
      kalori: 150,
      protein: 5,
      karbonhidrat: 27,
      yag: 2.5,
    },
    {
      isim: 'Elma',
      kalori: 95,
      protein: 0.5,
      karbonhidrat: 25,
      yag: 0.3,
    },
    {
      isim: 'Buharda Pişirilmiş Kuşkonmaz',
      kalori: 20,
      protein: 2.3,
      karbonhidrat: 3.7,
      yag: 0.2,
    },
    {
      isim: 'Dana Pirzola',
      kalori: 189,
      protein: 24,
      karbonhidrat: 0,
      yag: 9,
    },
    {
      isim: 'Üzüm',
      kalori: 69,
      protein: 0.7,
      karbonhidrat: 18,
      yag: 0.2,
    },
    {
      isim: 'Karpuz',
      kalori: 30,
      protein: 0.6,
      karbonhidrat: 7.6,
      yag: 0.2,
    },
    {
      isim: 'Kırmızı Biber',
      kalori: 40,
      protein: 1.3,
      karbonhidrat: 9.7,
      yag: 0.3,
    },
    {
      isim: 'Kızarmış Tavuk',
      kalori: 320,
      protein: 18,
      karbonhidrat: 17,
      yag: 20,
    },
    {
      isim: 'Mantar',
      kalori: 22,
      protein: 3.1,
      karbonhidrat: 3.3,
      yag: 0.3,
    },
    {
      isim: 'Limonata',
      kalori: 90,
      protein: 0.5,
      karbonhidrat: 23,
      yag: 0.1,
    },
    {
      isim: 'Çilek',
      kalori: 32,
      protein: 0.7,
      karbonhidrat: 7.7,
      yag: 0.3,
    },
    {
      isim: 'Karnabahar',
      kalori: 25,
      protein: 1.9,
      karbonhidrat: 5,
      yag: 0.3,
    },
    {
      isim: 'Pancar',
      kalori: 43,
      protein: 1.6,
      karbonhidrat: 9.6,
      yag: 0.2,
    },
    {
      isim: 'Peynir',
      kalori: 300,
      protein: 25,
      karbonhidrat: 1,
      yag: 22,
    },
    {
      isim: 'Tavuk Kanadı',
      kalori: 203,
      protein: 14,
      karbonhidrat: 0,
      yag: 17,
    },
  ];

  products.forEach(async (product) => {
    await Product.create({
      isim: product.isim,
      kalori: product.kalori,
      protein: product.protein,
      karbonhidrat: product.karbonhidrat,
      yag: product.yag,
    });
  });
};
